# Q 1

In [1]:
import numpy as np
arr1 = np.array([0.1, 2.5, 3.81, 41.4, 15.2,10.8])
arr2=np.array([['apple','banana','orange','cherry','mango'], ['papaya','kiwi','strawberry','grapes','plums']])
print(arr1)
print(arr2)

[ 0.1   2.5   3.81 41.4  15.2  10.8 ]
[['apple' 'banana' 'orange' 'cherry' 'mango']
 ['papaya' 'kiwi' 'strawberry' 'grapes' 'plums']]


# Q 2

In [2]:
print("type is: ",type(arr1))
print("dtype is: ",arr1.dtype)
print("type is: ",type(arr2))
print("dtype is: ",arr2.dtype)
arr1re=arr1.reshape(2,3)
print(arr1re)
arr2re=arr2.flatten()
print(arr2re)

type is:  <class 'numpy.ndarray'>
dtype is:  float64
type is:  <class 'numpy.ndarray'>
dtype is:  <U10
[[ 0.1   2.5   3.81]
 [41.4  15.2  10.8 ]]
['apple' 'banana' 'orange' 'cherry' 'mango' 'papaya' 'kiwi' 'strawberry'
 'grapes' 'plums']


# Q 3

In [3]:
import numpy as np
arr3=np.zeros([3,4],dtype=float)
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
arr4=np.ones(6,dtype=int)

print(arr4)

[1 1 1 1 1 1]


# Q 4

In [5]:
list1 = [10,20,30,40,50]
print(list1)

[10, 20, 30, 40, 50]


In [6]:
arr5=np.asarray(list1,dtype=float)
print(arr5)

[10. 20. 30. 40. 50.]


In [7]:
arr6=np.fromiter(list1,dtype=int,count=-1)
print(arr6)

[10 20 30 40 50]


# Q 5

In [8]:
arr7=np.arange(12,100,3)
print(arr7)

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


In [9]:
arr8=np.linspace(12,99,num=50,endpoint=True)
print(arr8)

[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


# Q 6

In [10]:
import numpy as np
arr2=np.array([['apple','banana','orange','cherry','mango'], ['papaya','kiwi','strawberry','grapes','plums']])
print(arr2) 

[['apple' 'banana' 'orange' 'cherry' 'mango']
 ['papaya' 'kiwi' 'strawberry' 'grapes' 'plums']]


In [11]:
print(arr2[0:1])

[['apple' 'banana' 'orange' 'cherry' 'mango']]


In [12]:
print(arr2[1][3])

grapes


In [13]:
print(arr2[1])

['papaya' 'kiwi' 'strawberry' 'grapes' 'plums']


# Q 7

In [14]:
import numpy as np
arr9=np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print(arr9)

[[101 322 768]
 [233 124 390]
 [534 122 216]]


In [15]:
arr10=arr9[0] [0],arr9[0][1],arr9[1][2],arr9[2][1]
print(arr10)

(101, 322, 390, 122)


In [16]:
arr11 =arr9[0:2,1:3]
print(arr11)

[[322 768]
 [124 390]]


# Q 8

In [17]:
print('Items that are greater than 200 are :')
print(arr9[arr9>200])

Items that are greater than 200 are :
[322 768 233 390 534 216]


In [18]:
print('non-NaN elements :')
print(arr9[~np.isnan(arr9)])

non-NaN elements :
[101 322 768 233 124 390 534 122 216]


In [19]:
print('non float elements :')
print (arr9[arr9.dtype!='float'])

non float elements :
[[[101 322 768]
  [233 124 390]
  [534 122 216]]]


In [20]:
arr15 = np.array([1,2,3])

In [21]:
print('arr9 : ')
print(arr9)
print('arr15 :')
print(arr15)
print('arr9 + arr15')
print(arr9 +arr15)

arr9 : 
[[101 322 768]
 [233 124 390]
 [534 122 216]]
arr15 :
[1 2 3]
arr9 + arr15
[[102 324 771]
 [234 126 393]
 [535 124 219]]


# Q 9

In [22]:
print('The Transpose of arr9 is given below :')
print(arr9.T)

The Transpose of arr9 is given below :
[[101 233 534]
 [322 124 122]
 [768 390 216]]


In [23]:
print(arr1)
print(arr4)
print('The joining of the arrays arr1 and arr4 along axis 0 : ')
x=np.concatenate((arr1,arr4),axis=0)
print(x)

[ 0.1   2.5   3.81 41.4  15.2  10.8 ]
[1 1 1 1 1 1]
The joining of the arrays arr1 and arr4 along axis 0 : 
[ 0.1   2.5   3.81 41.4  15.2  10.8   1.    1.    1.    1.    1.    1.  ]


# Q 10

In [24]:
import numpy as np
array2D=np.array([[1000,5000],[10000,40000]])
print(array2D)
a=np.hstack(array2D)
b=np.vstack(array2D)
c=np.hsplit(array2D,1)
d=np.vsplit(array2D,1)
print(a)
print(b)
print(c)
print(d)

[[ 1000  5000]
 [10000 40000]]
[ 1000  5000 10000 40000]
[[ 1000  5000]
 [10000 40000]]
[array([[ 1000,  5000],
       [10000, 40000]])]
[array([[ 1000,  5000],
       [10000, 40000]])]
