### 1.Create two numpy arrays. The first array, called arr1 should be of one dimension and consist of six elements of float type. The second array, called arr2 should be of two dimensions and each sub-array should consist of 5 elements of string type. Display these two numpy arrays.

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6],dtype=float)
print('Array1 :\n')
print(arr1)
print('-'*30)
arr2 = np.array([[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45],[51,52,53,54,55]],dtype=str)
print('Array2 :\n')
print(arr2)

Array1 :

[1. 2. 3. 4. 5. 6.]
------------------------------
Array2 :

[['11' '12' '13' '14' '15']
 ['21' '22' '23' '24' '25']
 ['31' '32' '33' '34' '35']
 ['41' '42' '43' '44' '45']
 ['51' '52' '53' '54' '55']]


### 2.For the arrays arr1 and arr2 created in Q.No.1, display the following properties: data type and dimensions. Reshape arr1 into a two dimensional array of 2 rows and three columns, and display the reshaped array. Similarly, reshape arr2 into a single dimensional array and display the reshaped array.

In [2]:
## display the following properties: data type and dimensions.
print('The datatype of arr1 {',arr1.dtype,'} and Dimensions of the arr1 :',np.shape(arr1))
print('The datatype of arr2 {',arr2.dtype,'} and Dimensions of the arr2 : ',np.shape(arr2))
print('-'*100)
print('Dimension of arr1 :',arr1.ndim,"Dimensional")
print('Dimension of arr2 :',arr2.ndim,"Dimensional")

The datatype of arr1 { float64 } and Dimensions of the arr1 : (6,)
The datatype of arr2 { <U2 } and Dimensions of the arr2 :  (5, 5)
----------------------------------------------------------------------------------------------------
Dimension of arr1 : 1 Dimensional
Dimension of arr2 : 2 Dimensional


In [3]:
# Reshape arr1 into a two dimensional array of 2 rows and 3 columns, and display the reshaped array.
re_arr1 = np.reshape(arr1,(2,3))

re_arr2 = np.reshape(arr2,(1,25))

print("Reshape arr1 into a two dimensional array of 2 rows and 3 columns :\n")
print(re_arr1)
print('-'*80)
print("Reshape arr2 into a single dimensional array :\n")
print(re_arr2)

Reshape arr1 into a two dimensional array of 2 rows and 3 columns :

[[1. 2. 3.]
 [4. 5. 6.]]
--------------------------------------------------------------------------------
Reshape arr2 into a single dimensional array :

[['11' '12' '13' '14' '15' '21' '22' '23' '24' '25' '31' '32' '33' '34'
  '35' '41' '42' '43' '44' '45' '51' '52' '53' '54' '55']]


### 3.Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes. Create another single dimensional array called arr4, with 6 elements and which is initialized to ones. The type of arr4 is int.

In [4]:
import numpy as np
arr3 = np.zeros([3,4],dtype=float)
print("arr3, of 3 rows and 4 columns which is initialized to zeroes :\nArray3 :")
print(arr3)
print("-"*80)
arr4 = np.ones(6,dtype=int)
print("arr4, with 6 elements of single dimensional array and which is initialized to ones:\nArray4 :")
print(arr4)

arr3, of 3 rows and 4 columns which is initialized to zeroes :
Array3 :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------------------------------------------------------------------
arr4, with 6 elements of single dimensional array and which is initialized to ones:
Array4 :
[1 1 1 1 1 1]


### 4.Create a list called list1 with the elements 10,20,30,40,50. Now, create a numpy array called arr5 from list1, using the method asarray. The data type of arr5 is float. Similarly, create another array called arr6, from list1, using the method fromiter, whose data type is int. Display arr5 and arr6.

In [5]:
list1 = [10,20,30,40,50]

arr5 = np.asarray(list1,dtype=float)
arr6 = np.fromiter(list1,dtype=int)

print('Asarray Method of arr5 :\n')
print(arr5)
print('-'*35)
print('Fromiter method of arr6 :\n')
print(arr6)

Asarray Method of arr5 :

[10. 20. 30. 40. 50.]
-----------------------------------
Fromiter method of arr6 :

[10 20 30 40 50]


### 5.Create a numpy array called arr7 using the method arange. The starting value of this array is 12 and ending value is 99, with a step size of 3. Use the linspace method to create another array called arr8, where the starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements.

In [6]:
arr7 = np.arange(12,100,3,int)
print("The starting value of this array is 12 and ending value is 99, with a step size of 3 : \n",'-'*100,"\narr7:\n")
print(arr7)
print('*'*100)
arr8 = np.linspace(12,99,50,endpoint = True)
print("The starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements : \n",'-'*100," \narr8:\n")
print(arr8)

The starting value of this array is 12 and ending value is 99, with a step size of 3 : 
 ---------------------------------------------------------------------------------------------------- 
arr7:

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]
****************************************************************************************************
The starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements : 
 ----------------------------------------------------------------------------------------------------  
arr8:

[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653

### 6.In the array arr2 defined in Q.No. 1, what is the output of the following statements: print(arr2), print(arr2[0:1]), print(arr2[1][3]), print (arr2[1]).

In [7]:
print("Array2 :\n")
print(arr2)

Array2 :

[['11' '12' '13' '14' '15']
 ['21' '22' '23' '24' '25']
 ['31' '32' '33' '34' '35']
 ['41' '42' '43' '44' '45']
 ['51' '52' '53' '54' '55']]


In [8]:
print("arr2[0:1] :\n")
print(arr2[0:1])

arr2[0:1] :

[['11' '12' '13' '14' '15']]


In [9]:
print("arr2[1][3] :\n")
print(arr2[1][3])

arr2[1][3] :

24


In [10]:
print("arr2[1] :\n")
print(arr2[1])

arr2[1] :

['21' '22' '23' '24' '25']


### 7.Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.

In [11]:
arr9 = np.array([[101,322,768],[233,124,390],[534,122,216]])
print("Dimensional array :",arr9.ndim,"\n")
print(arr9)

Dimensional array : 2 

[[101 322 768]
 [233 124 390]
 [534 122 216]]


#### *Advanced integer indexing*

In [12]:
print("Advanced Integer Indexing :\n")
arr10 = arr9[[0,0,1,2],[0,1,2,1]]
print(arr10)

Advanced Integer Indexing :

[101 322 390 122]


#### *elements of first and second rows, and second and third columns using slicing operations.*

In [13]:
print("arr11 which contains elements of first and second rows, and second and third columns :")
print("Slicing Operations :\n")
arr11 = arr9[0:2,(1,2)]
print(arr11)

arr11 which contains elements of first and second rows, and second and third columns :
Slicing Operations :

[[322 768]
 [124 390]]


### 8.From array arr9 created in Q.No. 7, find all elements greater than 200 using boolean indexing, find all non-NaN elements, and find all non-float elements. Find the result of adding arrays arr9 and another array of 3 elements, using the concept of broadcasting.

In [14]:
print("Array9 :")
print(arr9)

Array9 :
[[101 322 768]
 [233 124 390]
 [534 122 216]]


#### *find all elements greater than 200 using boolean indexing*

In [15]:
import numpy as np
x = np.array(arr9>200,dtype = bool)
print(x)

[[False  True  True]
 [ True False  True]
 [ True False  True]]


In [16]:
print('The elements greater than 200 :',arr9[arr9>200])

The elements greater than 200 : [322 768 233 390 534 216]


#### *find all non-NaN elements*

In [17]:
import numpy as np
x = np.array(~np.isnan(arr9),dtype = bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
print('All non-NaN elements :',arr9[~np.isnan(arr9)])

All non-NaN elements : [101 322 768 233 124 390 534 122 216]


#### *find all non-float elements.*

In [19]:
print('All non-float elements :\n\n',arr9[arr9.dtype!='float'])

All non-float elements :

 [[[101 322 768]
  [233 124 390]
  [534 122 216]]]


In [20]:
import numpy as np
x = np.array(arr9.dtype!='float')
y = np.array(x,dtype = bool)
print(y)

True


#### *concept of broadcasting*

In [21]:
print("Array9 :\n")
print(arr9)
print("\nArray12 :\n")
arr12 = np.array([21,13,5])
print(arr12)

Array9 :

[[101 322 768]
 [233 124 390]
 [534 122 216]]

Array12 :

[21 13  5]


In [22]:
print('Adding of arr9 + arr12 arrays using broadcasting :\n')
print(arr12 + arr9)

Adding of arr9 + arr12 arrays using broadcasting :

[[122 335 773]
 [254 137 395]
 [555 135 221]]


### 9.For the array arr9, find its transpose. Find the result of joining the arrays arr1 and arr4 along axis 0

#### *array arr9, find its transpose*

In [23]:
print('Array9 :\n',arr9)
print('\nThe Transpose of arr9 is given below :\n')
print(arr9.T)

Array9 :
 [[101 322 768]
 [233 124 390]
 [534 122 216]]

The Transpose of arr9 is given below :

[[101 233 534]
 [322 124 122]
 [768 390 216]]


#### *the result of joining the arrays arr1 and arr4 along axis 0the result of joining the arrays arr1 and arr4 along axis 0*

In [24]:
print(arr1)
print(arr4)
print('-'*80)
print('The joining of two arrays are arr1 and arr4 given below :\n')
arr = np.concatenate((arr1,arr4),axis=0)
print(arr)

[1. 2. 3. 4. 5. 6.]
[1 1 1 1 1 1]
--------------------------------------------------------------------------------
The joining of two arrays are arr1 and arr4 given below :

[1. 2. 3. 4. 5. 6. 1. 1. 1. 1. 1. 1.]


### 10.Using any two 2-dimensional arrays, demonstrate the working of the methods, hstack, vstack, hsplit and vsplit

In [28]:
import numpy as np
arr13 = np.array([[21,13],[19,24]])
print(arr13)
print('-'*20)
arr14=np.hstack(arr13)
arr15=np.vstack(arr13)
arr16=np.hsplit(arr13,1)
arr17=np.vsplit(arr13,1)
print("hstack :\n",arr14)
print('-'*20)
print("vstack :\n",arr15)
print('-'*20)
print("hsplit :\n",arr16)
print('-'*20)
print("vsplit :\n",arr17)

[[21 13]
 [19 24]]
--------------------
hstack :
 [21 13 19 24]
--------------------
vstack :
 [[21 13]
 [19 24]]
--------------------
hsplit :
 [array([[21, 13],
       [19, 24]])]
--------------------
vsplit :
 [array([[21, 13],
       [19, 24]])]


In [29]:
arr14 = np.hstack((arr13,arr13))
arr15 = np.vstack((arr13,arr13))
print("hstack :\n",arr14)
print('-'*20)
print("vstack :\n",arr15)

hstack :
 [[21 13 21 13]
 [19 24 19 24]]
--------------------
vstack :
 [[21 13]
 [19 24]
 [21 13]
 [19 24]]


In [30]:
arr16=np.hsplit(arr13,2)
arr17=np.vsplit(arr13,2)
print("hsplit :\n",arr16)
print('-'*20)
print("vsplit :\n",arr17)

hsplit :
 [array([[21],
       [19]]), array([[13],
       [24]])]
--------------------
vsplit :
 [array([[21, 13]]), array([[19, 24]])]
