# NUMPY INTRODUCTION

In [1]:
# NUMPY is a python library function used for working with arrays
# it as also function for domain of linear algebra, forurier transformer and matrices.
# NUMPY is a numerical python.
# numpy as working with the array object in numpy is called ndarray.
# NUMPY as np

In [2]:
import numpy 
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
print(np.__version__)

1.20.3


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))  # list, tuple of methods can be converted as ndarray:
print(arr)

[1 2 3 4 5]


In [9]:
#dimensional in array
# a dimensional array is one level of the depth nested array
# 0 -D Array
import numpy as np
arr = np.array(42)
print(arr)

42


In [10]:
# 1 -D Array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [13]:
# 2 -D array
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
# 3 - D Array
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 6 9]]]


In [17]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
# HIGHER DIMENSIONAL ARRAY
# you acn defined the number of dimensions by using the ndmin argument
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)
print("number of dimensions in array:", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions in array: 5


In [31]:
# NUMPY ARRAY ELEMENTS
# Array indexing is e same as accessing an array elements
#you can access the an array element by referring to its index number
# index numpy array start with the 0, as second digit as the 1
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [33]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print('2nd element on 1st row: ', arr[0, 1])
            #arr[first list of first index in, second index]

2nd element on 1st row:  2


In [34]:
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
print(arr[0,1,2])

6


In [36]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print('print last element of last dimension:',arr[1,-1])

print last element of last dimension: 6


In [49]:
# NUMPY ARRAY SLICING
# SLICING ARRAYS [START:END:STEP]
# pass slice of index [start:end]
# can aslo defined a step [start:end:step]
# if don't pass start consider 0
# if don't pass end consider length of array in that dimension
# if don't step end consider 1
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[1:5]) # start is mentioned its show if end is mentioned not show
print(arr[0:])
print(arr[:5])
print(arr[-3:-1]) # end not mentionedits comes from back
print(arr[1:5:2])
print(arr[1:6:4])
print(arr[1:6:6]) # missing of between elements from the start to step menstioned element
print(arr[::2])

[2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5]
[4 5]
[2 4]
[2 6]
[2]
[1 3 5]


In [60]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr[1, 1:4])
print(arr[0, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1]) # end of index with both the array of index

[5 6]
[2 3]
[3 6]
[2 5]


In [73]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr[0:2, 1:4])
print(arr[0:3, 0:1]) 
print(arr[0:2, 0:2])
print(arr[0:3, 1:2]) # similer index to get the same dim if unsimilar the dim not applicable

[[2 3]
 [5 6]]
[[1]
 [4]]
[[1 2]
 [4 5]]
[[2]
 [5]]


In [74]:
# DATA TYPES IN PYTHON
# strings - ABCD
# integer - 1,2,3
# float - 1.2,3.4,5.3
# boolean - True, False
# complex - 1.0+2.0j

In [75]:
# DATA TYPES IN NUMPY
# i - integer
# b - boolean
# u - unsigned integer
# f - float 
# c - complex float
# m - timedelota
# M - datatime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type

In [78]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int32


In [82]:
import numpy as np
arr = np.array(['a', 'b', 'c', 'd'])
print(arr.dtype)

<U1


In [87]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7], dtype = 'S')
print(arr)
print(type(arr))
print(arr.dtype) # FOR i, u, f, S and U

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
<class 'numpy.ndarray'>
|S1


In [90]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7], dtype = 'i4')
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int32


In [91]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [92]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [94]:
import numpy as np
arr = np.array([1.1, 0, 3.1])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [96]:
# NUMPY ARRAY COPY VS VIEW 
# copy:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [97]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [99]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[2] = 32
print(arr)
print(x)

[ 1  2 32  4  5]
[ 1  2 32  4  5]


In [102]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [105]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[2] = 42
print(arr)
print(x.base)
print(y.base)

[ 1  2 42  4  5]
None
[ 1  2 42  4  5]


In [108]:
# NUMPY IN ARRAY SHAPE
# shape of an array
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.shape)

(2, 3)


In [109]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print('shape of array:',arr.shape)

shape of array: (4,)


In [112]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [113]:
# NUMPY IN RESHAPE
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [114]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [117]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [120]:
# RETURN COPY OR VIEW
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [121]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
# NUMPY ARRAY iterating
#iterating arrays
# multiple dimensions in numpy we use the for loop
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [4]:
# iterating 2-D arrays
import numpy as np
arr = ([[1, 2, 3],[4, 5, 6]])
for x in arr:
    print(x)

[1, 2, 3]
[4, 5, 6]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [7]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [8]:
# iterating 3-D array
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [3 6 9]]


In [9]:
import numpy as np 
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
for x in arr:
    for y in x:
        for z in x:
            print(z)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
[7 8 9]
[3 6 9]
[7 8 9]
[3 6 9]


In [10]:
import numpy as np 
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[3, 6, 9]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
3
6
9


In [12]:
# iterating arrays using nditer()
# nditer() very advanced function number of iterations
# iterating on each scalar element
import numpy as np
arr = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [14]:
# ITERATING ARRAY WITH DIFFERENT DATA TYPES
# OP_DTYPES 
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(x)

b'1'
b'2'
b'3'


In [15]:
# skipping first elements
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
4
6


In [17]:
# ENUMERATE is use as sequence of ac number
import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [18]:
import numpy as np
arr = np.array(["vinay", "pravali", "haritha", "hema vennala"])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) vinay
(1,) pravali
(2,) haritha
(3,) hema vennala


In [20]:
# NUMPY JOINING ARRAY
# joining numpy arrays
# two are more arrays in a single array
# sequnece of array they want to join the concatenate()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [21]:
import numpy as np
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
arr = np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [22]:
# JOING ARRAY USING STACK FUNCTIONS 
# STACKING IS AS SAME AS CONCATENATE
# THEY ONLY DIFFERENCE IS THE NEW AXIS
import numpy as np
arr1 = ([1, 2, 3])
arr2 = ([4, 5, 6])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# STACKING ALONG ROWS
# numpy provides a helper function: hstack() to
# stack along rows.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [24]:
# STACKING ALONG colomn
# numpy provides a helper function: vstack() to
# stack along colomn.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
# stacking along height (depth)
# dstack
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [26]:
# NUMPY SPLITING ARRAY
# SPLITTING NUMPY ARRAYS
# spliting is the reverse operation of the joinng 
# joining merges multiple arrays into one and splitting breaks one array into multiple.
# we use splitting array (array_split())
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [28]:
#splitting arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [29]:
import numpy as np
arr = np.array([[1, 2],[3,4],[5, 6],[6, 7],[8, 9],[10, 11],[12, 13]])
newarr = np.array_split(arr, 3)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


In [34]:
import numpy as np
arr = np.array([[1, 2],[3,4],[5, 6],[6, 7],[8, 9],[10, 11],[12, 13]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[6, 7],
       [8, 9]]), array([[10, 11],
       [12, 13]])]


In [33]:
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.array_split(arr, 3)
print(arr)

[[ 1  2  4]
 [ 3  4  8]
 [ 5  6  7]
 [ 6  7  2]
 [ 8  9  7]
 [10 11  3]
 [12 13  4]]


In [36]:
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.array_split(arr, 5)
print(newarr)

[array([[1, 2, 4],
       [3, 4, 8]]), array([[5, 6, 7],
       [6, 7, 2]]), array([[8, 9, 7]]), array([[10, 11,  3]]), array([[12, 13,  4]])]


In [37]:
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.array_split(arr, 5, axis = 1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 6],
       [ 8],
       [10],
       [12]]), array([[ 2],
       [ 4],
       [ 6],
       [ 7],
       [ 9],
       [11],
       [13]]), array([[4],
       [8],
       [7],
       [2],
       [7],
       [3],
       [4]]), array([], shape=(7, 0), dtype=int32), array([], shape=(7, 0), dtype=int32)]


In [39]:
# hsplit() is opposite to hstack()
import numpy as np
arr = np.array([[1, 2, 4],[3, 4, 8],[5, 6, 7],[6, 7, 2],[8, 9, 7],[10, 11, 3],[12, 13, 4]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 6],
       [ 8],
       [10],
       [12]]), array([[ 2],
       [ 4],
       [ 6],
       [ 7],
       [ 9],
       [11],
       [13]]), array([[4],
       [8],
       [7],
       [2],
       [7],
       [3],
       [4]])]


In [47]:
# vstack() and dstack() is similar to
# vsplit() and dsplit()

In [48]:
# NUMPY SEARCHING ARRAY
# Searching arrays
# you can a search asertain value we get the index value to find the number
# to search the array we use the where() method
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr == 4)
print(x)

(array([3], dtype=int64),)


In [49]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 7, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 7], dtype=int64),)


In [50]:
import numpy as np
arr = np.array([1, 2, 3, 4])
x = np.where(arr == 4)
print(x)

(array([3], dtype=int64),)


In [51]:
# WE FIND THE EVEN NUMBER FROM THE ARRAY
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [52]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6, 8], dtype=int64),)


In [54]:
# SEARCH SHORTED 
# searchsorted() to find its index value
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [55]:
# search form right side
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side = 'right')
print(x)

2


In [56]:
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [58]:
# NUMPY SORTING ARRAY
# SORTING ARRAY
# sort means putting elements in order sequence
# order sequence in numeric, alphabet, ascending or descending.
# the numpy ndarray object has a function called sort()
import numpy as np
arr = np.array([3, 6, 5, -6])
print(np.sort(arr))

[-6  3  5  6]


In [59]:
import numpy as np
arr = np.array(["egg","apple","rinbow","cat","ball"])
print(np.sort(arr))

['apple' 'ball' 'cat' 'egg' 'rinbow']


In [60]:
import numpy as np
arr = np.array(["flag","fight","from","for","fare"])
print(np.sort(arr))

['fare' 'fight' 'flag' 'for' 'from']


In [64]:
import numpy as np
arr = np.array([[1, 2],[3, 4]])
print(np.sort(arr))

[[1 2]
 [3 4]]


In [65]:
import numpy as np
arr = np.array([[1, 5, 2],[6, 4, 1]])
print(np.sort(arr))

[[1 2 5]
 [1 4 6]]


In [67]:
import numpy as np
arr = np.array([41, 42 , 43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


In [68]:
# craeting the filter array
import numpy as np
arr = np.array([41, 42, 43, 44])

#craete an empty list
filter_arr = []
# go through the elementin array
for element in arr:
    #if the element is heigher then the 4,
    # set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [70]:
# craeting the filter array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#craete an empty list
filter_arr = []

# go through the elementin array
for element in arr:
    #if the element is divisible by 2,
    # set the value to True, otherwise False:
    if element %2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [72]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [75]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]
