# Numpy
Numpy stands for numerical python
It is a library used to perform scientific and mathematical computation on array


# Array
Array is a datastructure of numpy.Array is homogenous and faster than list and also you can perform many mathematical inbuilt operations on an array
Array can be multidimensional but list is unidimensional

In [1]:
# importing library
import numpy as np # import is used to import the library , np is the alias name 


# Creating an array
## From a list
## Using numpy functions
## Special functions


In [7]:
#From a list
import numpy as np
list=[1,2,3,4,5,6,7,7,8,14.4,'Devang']
first_array=np.array(list)
first_array

array(['1', '2', '3', '4', '5', '6', '7', '7', '8', '14.4', 'Devang'],
      dtype='<U32')

In [8]:
first_array.dtype

dtype('<U32')

In [119]:
#Numpy function 
second_array= np.array([1,1,2,3,4,5,6,7,8])
two_d_array=np.array([[1,2,4,5,6],[56,75,67,59,10]])
two_d_array
print(second_array.ndim)
print(two_d_array.ndim)
print(type(second_array))

# no of Square brackets will determine the dimension

#11th,12th--> Matrix 

1
2
<class 'numpy.ndarray'>


In [103]:
print(second_array.shape)
print(two_d_array.shape)

print(second_array.size)
print(two_d_array.size)

(9,)
(2, 5)
9
10


In [104]:
second_array.dtype

dtype('int32')

In [6]:
# 2 D Array
first_2d_array=np.array([[1,13,49,5,6,7],[1,3,5,27,18,8]])

In [124]:
first_2d_array
first_2d_array.sort()
print(first_2d_array)

[[ 1  5  6  7 13 49]
 [ 1  3  5  8 18 27]]


In [8]:
first_3d_array=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [9]:
first_3d_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# Some important parameters
1.Shape
2.Size
3.Dimension
4.Data type

In [10]:
#Creating array from special functions
special_array1=np.zeros([4,4])

In [11]:
special_array1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
special_array2=np.eye(4,4)

In [106]:
special_array2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
special_array3=np.arange(20).reshape(2,10)

In [110]:
special_array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
special_array4=np.ones([3,4])

In [17]:
special_array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
special_array5=np.full((3,3),10)

In [112]:
special_array5


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [115]:
special_array6=np.linspace(0,20,4)

In [116]:
special_array6

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [117]:
special_array7=np.random.random((3,2))

In [118]:
special_array7

array([[0.95664692, 0.49886422],
       [0.22840516, 0.02862718],
       [0.42927527, 0.77465415]])

# Examining numpy array
1.Shape
2.Size
3.Dimension
4.Data type
5.Type

In [24]:
#shape
first_array.shape

(10,)

In [25]:
#size
first_array.size

10

In [26]:
#dimensions
first_array.ndim

1

In [27]:
#type
type(first_array)

numpy.ndarray

In [28]:
#dtype
first_array.dtype

dtype('int32')

# Manipulating the array
1.Sorting
2.Flatten
3.Transpose
4.Reshape
5.Copy
6.Resize
7.Append
8.Insert
9.Delete

In [120]:
#sort
first_2d_array.sort()
print(first_2d_array)

[[ 1  5  6  7 13 49]
 [ 1  3  5  8 18 27]]
[[ 1  5  6  7 13 49]
 [ 1  3  5  8 18 27]]


In [126]:
#flatten
arr=first_2d_array.flatten()
arr

array([ 1,  5,  6,  7, 13, 49,  1,  3,  5,  8, 18, 27])

In [31]:
first_2d_array.shape

(2, 6)

In [32]:
#Transpose
first_2d_array.T

array([[ 1,  1],
       [ 5,  3],
       [ 6,  5],
       [ 7,  8],
       [13, 18],
       [49, 27]])

In [128]:
#Reshaping
first_2d_array.reshape(4,3)

array([[ 1,  5,  6],
       [ 7, 13, 49],
       [ 1,  3,  5],
       [ 8, 18, 27]])

In [129]:
#Copy
arr=np.copy(first_2d_array)

In [130]:
#Resize
arr.resize((5,5))

In [131]:
arr

array([[ 1,  5,  6,  7, 13],
       [49,  1,  3,  5,  8],
       [18, 27,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [37]:
#Append
np.append(arr,[2,4,5,6,8])


array([ 1,  5,  6,  7, 13, 49,  1,  3,  5,  8, 18, 27,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  4,  5,  6,
        8])

In [136]:
#Insert
np.insert(arr,5,10)

array([ 1,  5,  6,  7, 13, 10, 49,  1,  3,  5,  8, 18, 27,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0])

In [135]:
#Delete
np.delete(arr,2,axis=0)

array([[ 1,  5,  6,  7, 13],
       [49,  1,  3,  5,  8],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

# Index and Slicing
Similar to list in single dimensional array but its a bit different for 2-d array and 3-array 
indexing refers to the position at which an element is placed 
slicing refers to calling the object/s at a particular position/s

In [138]:
#indexing and slicing 1-d array 
a = np.arange(10) 
print(a)

s = slice(2,9,2) 
print (a[s])

d=a[9]
print(d)

r=a[3:]
print(r)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]
9
[3 4 5 6 7 8 9]


In [41]:
#slicing and indexing 2-d array
ap = np.array([[11,2,23],[33,44,5],[84,25,16]])
i=ap[1,] #ap[row,column]
print(i)

x=ap[:,1]
print(x)

u=ap[2,2]
print(u)

y=ap[1,0]
print(y)

ap[2,2]=15
ap[1,1]=50
ap[0,0]=25

print(ap)

[33 44  5]
[ 2 44 25]
16
33
[[25  2 23]
 [33 50  5]
 [84 25 15]]


# Scalar Mathematics
Scalar operations include
1.Add
2.Subtract
3.Multiply
4.Divide
5.Power

In [42]:
np.add(ap,1)

array([[26,  3, 24],
       [34, 51,  6],
       [85, 26, 16]])

In [43]:
np.subtract(ap,3)

array([[22, -1, 20],
       [30, 47,  2],
       [81, 22, 12]])

In [44]:
np.multiply(ap,2)

array([[ 50,   4,  46],
       [ 66, 100,  10],
       [168,  50,  30]])

In [45]:
np.divide(ap,2)

array([[12.5,  1. , 11.5],
       [16.5, 25. ,  2.5],
       [42. , 12.5,  7.5]])

In [46]:
np.power(ap,3)

array([[ 15625,      8,  12167],
       [ 35937, 125000,    125],
       [592704,  15625,   3375]], dtype=int32)

# Vector Operations
Vector Operations 
1.Add
2.Subtract
3.Multiply
4.Divide
5.Power
6.Is_equal
7.sqrt
8.sin,log,abs,floor,ceil,round


In [47]:
ds= np.array([[1,2,3],[4,5,6],[7,8,9]])
np.add(ap,ds)

array([[26,  4, 26],
       [37, 55, 11],
       [91, 33, 24]])

In [48]:
np.subtract(ap,ds)

array([[24,  0, 20],
       [29, 45, -1],
       [77, 17,  6]])

In [49]:
np.divide(ap,ds)

array([[25.        ,  1.        ,  7.66666667],
       [ 8.25      , 10.        ,  0.83333333],
       [12.        ,  3.125     ,  1.66666667]])

In [50]:
np.multiply(ap,ds)

array([[ 25,   4,  69],
       [132, 250,  30],
       [588, 200, 135]])

In [51]:
np.power(ap,ds)

array([[         25,           4,       12167],
       [    1185921,   312500000,       15625],
       [-1685635072, -2030932031,  -211346289]], dtype=int32)

In [52]:
np.sqrt(ap)

array([[5.        , 1.41421356, 4.79583152],
       [5.74456265, 7.07106781, 2.23606798],
       [9.16515139, 5.        , 3.87298335]])

In [53]:
np.equal(ap,ds)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [54]:
np.sin(ap)


array([[-0.13235175,  0.90929743, -0.8462204 ],
       [ 0.99991186, -0.26237485, -0.95892427],
       [ 0.73319032, -0.13235175,  0.65028784]])

In [55]:
np.log(ap)

array([[3.21887582, 0.69314718, 3.13549422],
       [3.49650756, 3.91202301, 1.60943791],
       [4.4308168 , 3.21887582, 2.7080502 ]])

In [56]:
np.abs(ap)

array([[25,  2, 23],
       [33, 50,  5],
       [84, 25, 15]])

# Statistical Functions



In [57]:
np.mean(ap)

29.11111111111111

In [58]:
np.median(ap)

25.0

In [59]:
np.max(ap)

84

In [60]:
np.min(ap)

2

In [61]:
np.corrcoef(ap)

array([[ 1.        , -0.73686815,  0.45080483],
       [-0.73686815,  1.        ,  0.27126169],
       [ 0.45080483,  0.27126169,  1.        ]])

In [62]:
np.percentile(ap,25)

15.0

In [63]:
np.var(ap)

561.2098765432098

In [64]:
np.std(ap)

23.68986864765632

# Concatenation  Split Stack BroadCasting

In [65]:
np.concatenate((ap,ds),axis=0)

array([[25,  2, 23],
       [33, 50,  5],
       [84, 25, 15],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [66]:
np.concatenate((ap,ds),axis=1)

array([[25,  2, 23,  1,  2,  3],
       [33, 50,  5,  4,  5,  6],
       [84, 25, 15,  7,  8,  9]])

In [89]:
np.split(ap,3)


[array([[25,  2, 23]]), array([[33, 50,  5]]), array([[84, 25, 15]])]

In [68]:
np.hsplit(ap,3)

[array([[25],
        [33],
        [84]]),
 array([[ 2],
        [50],
        [25]]),
 array([[23],
        [ 5],
        [15]])]

In [91]:
np.matmul(ap,ds)


array([[194, 244, 294],
       [268, 356, 444],
       [289, 413, 537]])

In [70]:
np.hstack(ap)

array([25,  2, 23, 33, 50,  5, 84, 25, 15])

In [71]:
np.vstack(ap)

array([[25,  2, 23],
       [33, 50,  5],
       [84, 25, 15]])

In [83]:
vs=np.array([1,3,5])
broad_cast=vs+ap


In [81]:
broad_cast

array([[26,  5, 28],
       [34, 53, 10],
       [85, 28, 20]])

# Application of arrays
1.Working with the image dataset
2.Machine Learning Model
3.Statistical Summary


In [86]:
#Examples of Application 
#Finding IQR

import numpy as np

#define array of data
data = np.array([14, 19, 20, 22, 24, 26, 27, 30, 30, 31, 36, 38, 44, 47,50,55,100,125,150])

#calculate interquartile range 
q3, q1 = np.percentile(data, [75 ,25])
iqr = q3 - q1

#display interquartile range 
iqr



23.5

In [87]:
## Outliers Detection
import numpy as np
## Website analytics data:
## (row = day), (col = users, bounce, duration)
a = np.array([[815, 70, 115],
              [767, 80, 50],
              [912, 74, 77],
              [554, 88, 70],
              [1008, 65, 128]])
mean, stdev = np.mean(a, axis=0), np.std(a, axis=0)
 #Mean: [811.2  76.4  88. ]
#Std: [152.97764543   6.85857128  29.04479299]
## Find Outliers
outliers = ((np.abs(a[:,0] - mean[0]) > stdev[0])
            * (np.abs(a[:,1] - mean[1]) > stdev[1])
            * (np.abs(a[:,2] - mean[2]) > stdev[2]))
## Result
print(a[outliers])

[[1008   65  128]]
