In [1]:
#Numpy --> Numerical Python 
#It is a python library mainly used for scientific and numerical computation
#The data type we have it is array

#How array and a list is different from each other 
#Array has one data type for all the elements in particular array whereas
#list can support multiple data types in one list

#Array can be multidimensional but list is only single dimensional 

#Arrays are faster than list 

#Array has many functionalities for computation as compared to list




In [2]:
#Q1)---> Which of these is not an application of numpy array?
#A)--> outlier detection
#B)--> dealing with images
#C)--> finding a particular element or a condition in a dataset
#D)-->Generating some random numbers 

#D)


In [5]:
#Q5)--> 1)--> using numpy .arange create an array which has 99 as the last val and 12 with a difference of 3
x=np.arange(12,100,3)
x

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [8]:
y=np.zeros((3,3)) #will initialize all elements as 0

In [9]:
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
z=np.ones((3,3)) #it will initialize all elements as 1


In [14]:
a=np.eye(3,3) #it will create a diagnol matrix for a given shape

In [15]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.linspace(10,20,5) #it will fill the array with the no of elements at a given interval between 2 numbers

array([10. , 12.5, 15. , 17.5, 20. ])

In [18]:
#[4*4 with only diagnols having 1s and rest all are 0]
np.eye(4,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [19]:
#inspecting 
x=np.array([1,2,3,4,5])

In [42]:
y=np.array([[[1,2,3,4],[5,6,7,8]]])

In [39]:
np.shape(x)

(5,)

In [43]:
np.shape(y) #shape(x,y) #x--> always gives no of rows and y will give no of columns

(1, 2, 4)

In [23]:
#shape will return the shape of array

np.size(x) #return the total no of elements

5

In [24]:
np.size(y)

8

In [31]:
x.dtype #it will return data type of the entire array

dtype('int32')

In [32]:
y.dtype

dtype('int32')

In [34]:
x.ndim

1

In [44]:
y.ndim

3

In [46]:
x.view()

array([1, 2, 3, 4, 5])

In [52]:
#Manipulation
#Reshape
#Resize

#y.reshape(1,8)#no of rows*col== size #will change the shape
y.resize((2,10),refcheck=False) #will change the size 

In [54]:
y.flatten() #flatten will convert any dimensional array into one dimension

array([1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
y.resize((4,8),refcheck=False) #refcheck =true #reshape

In [59]:
y

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#1.Scalar 
#2.Vector 
#3.Mathematical operation
#4.Hstack,vstack,concat,hsplit 


In [73]:
#Mean,median,percentile,std,variance,max,min
x=np.percentile(a=[1,2,3,4,5,6,7],q=25)
y=[1,2,3,4,5,np.nan]
y

[1, 2, 3, 4, 5, nan]

In [62]:
print('The 25th percentile value of a is',x)

The 25th percentile value of a is 2.5


In [63]:
a=[1,3,4,5,5,2,52,52,5,22,5,24,35,24,3,4,245,44,3,53,35,33,34,39,35,3,53,5,34,35]

In [77]:
#mean,median,std,min,max,var,#25%,75%
#statistical summary 

print('Mean of data is',np.mean(a))
print('Median of the data is',np.median(a))
print('Standard deviation of data is',np.std(a))
print('Minimum value of data is',np.min(a))
print('Maximum value of data is',np.max(a))
print('Variance of the data is',np.var(a))
print('1st Quartile of data is',np.quantile(a,0.25))
print('3rd Quartile of data is',np.percentile(a,q=75))
print('IQR of data is',(np.percentile(a,q=75))-(np.percentile(a,q=25)))

Mean of data is 29.9
Median of the data is 24.0
Standard deviation of data is 43.90242969737932
Minimum value of data is 1
Maximum value of data is 245
Variance of the data is 1927.4233333333334
1st Quartile of data is 4.25
3rd Quartile of data is 35.0
IQR of data is 30.75


In [79]:
#Outlier  Z score
from scipy.stats import zscore
z=np.abs(zscore(a))

In [80]:
z


array([0.65827792, 0.61272235, 0.58994457, 0.56716679, 0.56716679,
       0.63550014, 0.503389  , 0.503389  , 0.56716679, 0.17994448,
       0.56716679, 0.13438892, 0.11616669, 0.13438892, 0.61272235,
       0.58994457, 4.89950104, 0.32116673, 0.61272235, 0.52616678,
       0.11616669, 0.07061113, 0.09338891, 0.20727782, 0.11616669,
       0.61272235, 0.52616678, 0.56716679, 0.09338891, 0.11616669])

In [81]:
threshold=3
#mean-3 std to mean+3std --> normal value
print(np.where(z>3))


(array([16], dtype=int64),)


In [83]:
print('Outlier is',a[16])

Outlier is 245


In [91]:
#Indexing and slicing
b=np.resize(a,(3,30))
b

array([[  1,   3,   4,   5,   5,   2,  52,  52,   5,  22,   5,  24,  35,
         24,   3,   4, 245,  44,   3,  53,  35,  33,  34,  39,  35,   3,
         53,   5,  34,  35],
       [  1,   3,   4,   5,   5,   2,  52,  52,   5,  22,   5,  24,  35,
         24,   3,   4, 245,  44,   3,  53,  35,  33,  34,  39,  35,   3,
         53,   5,  34,  35],
       [  1,   3,   4,   5,   5,   2,  52,  52,   5,  22,   5,  24,  35,
         24,   3,   4, 245,  44,   3,  53,  35,  33,  34,  39,  35,   3,
         53,   5,  34,  35]])

In [90]:
b[1,3:16]

array([ 5,  5,  2, 52, 52,  5, 22,  5, 24, 35, 24,  3,  4])

In [92]:
#b[#row,#col]
b[:2,4:18]

array([[  5,   2,  52,  52,   5,  22,   5,  24,  35,  24,   3,   4, 245,
         44],
       [  5,   2,  52,  52,   5,  22,   5,  24,  35,  24,   3,   4, 245,
         44]])